[package]
name = "ya-runtime-wasi"
version = "0.3.0"
authors = ["Golem Factory <contact@golem.network>"]
edition.workspace = true
rust-version.workspace = true
license = "GPL-3.0"
description="Yagna WASI runtime embedding API"
readme = "README.md"
repository = "https://github.com/golemfactory/ya-runtime-wasi"
homepage = "https://github.com/golemfactory/ya-runtime-wasi"
documentation = "https://docs.rs/ya-runtime-wasi"

[dependencies]
anyhow.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
wasmparser.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
ya-runtime-api = "0.7.0"
zip.workspace = true

[dev-dependencies]
env_logger.workspace = true
tempfile.workspace = true
wat = "1.256.0"

[build-dependencies]
anyhow.workspace = true
zip.workspace = true

[features]
integration-tests = []
sgx=[]
