name: Release
on:
  push:
    tags:
      - v*
      - pre-rel-*

permissions:
  contents: write

jobs:
  create-rel:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create "$GITHUB_REF_NAME" --prerelease --generate-notes --verify-tag
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}-latest
    needs: create-rel
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - name: Install Rust 1.97
        shell: bash
        run: |
          rustup toolchain install 1.97.0 --profile minimal
          rustup default 1.97.0
      - name: Cargo Deb
        if: matrix.os == 'ubuntu'
        run: cargo install cargo-deb --locked
      - name: Build Deb
        if: matrix.os == 'ubuntu'
        run: cargo deb
      - name: Build
        run: cargo build --release --locked
      - name: Pack
        id: pack
        shell: bash
        env:
          OS_NAME: ${{ matrix.os }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          if [ "$OS_NAME" = "ubuntu" ]; then
            OS_NAME=linux
            deb_files=(target/debian/*.deb)
            deb_name=${deb_files[0]##*/}
            echo "deb=$deb_name" >> "$GITHUB_OUTPUT"
          elif [ "$OS_NAME" == "macos" ]; then
            OS_NAME=osx
          fi
          TARGET_DIR=releases/ya-runtime-wasi-${OS_NAME}-${TAG_NAME}

          mkdir -p "$TARGET_DIR"
          cp target/release/ya-runtime-wasi.json "$TARGET_DIR/"
          if [ "$OS_NAME" = "windows" ]; then
              cp target/release/ya-runtime-wasi.exe "$TARGET_DIR/"
              strip "$TARGET_DIR/ya-runtime-wasi.exe"
          else
              cp target/release/ya-runtime-wasi "$TARGET_DIR/"
              strip "$TARGET_DIR/ya-runtime-wasi"
          fi
          ls -al "$TARGET_DIR"
          if [ "$OS_NAME" = "windows" ]; then
              echo "artifact=ya-runtime-wasi-${OS_NAME}-${TAG_NAME}.zip" >> "$GITHUB_OUTPUT"
              (cd "$TARGET_DIR" && 7z a "../ya-runtime-wasi-${OS_NAME}-${TAG_NAME}.zip" * )
          else
              echo "artifact=ya-runtime-wasi-${OS_NAME}-${TAG_NAME}.tar.gz" >> "$GITHUB_OUTPUT"
              (cd releases && tar czvf "ya-runtime-wasi-${OS_NAME}-${TAG_NAME}.tar.gz" "ya-runtime-wasi-${OS_NAME}-${TAG_NAME}")
          fi
      - name: Upload Deb
        if: matrix.os == 'ubuntu'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "$GITHUB_REF_NAME" "./target/debian/${{ steps.pack.outputs.deb }}"
      - name: Upload Release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "$GITHUB_REF_NAME" "./releases/${{ steps.pack.outputs.artifact }}"
