name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - v[0-9]*

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    steps:
    - uses: actions/checkout@v6
      with:
        lfs: true
    - name: Install Rust 1.97
      shell: bash
      run: |
        rustup toolchain install 1.97.0 --profile minimal --component rustfmt,clippy --target wasm32-wasip1
        rustup default 1.97.0
    - name: Cargo fmt
      run: cargo fmt --all -- --check
    - name: Cargo build
      run: cargo build --workspace --all-targets
    - name: Cargo test
      run: cargo test --workspace --all-targets --features integration-tests
    - name: Cargo clippy
      if: matrix.os == 'linux'
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
